name: do_quran
description: Dongkap | Al Qur'an Mobile Application with Flutter (Android & iOS).
publish_to: 'none'
version: 1.0.0+1
homepage: https://github.com/ridlafadilah/do-quran
repository: https://github.com/ridlafadilah/do-quran

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.8.1
  flutter_launcher_icons: ^0.8.1
  package_info: ^0.4.3+2
  scrollable_positioned_list: ^0.1.9
  progress_indicators: ^0.1.5
  google_fonts_arabic: ^1.1.7
  geolocator: ^6.1.14
  geocoding: ^1.0.5
  flutter_compass: ^0.5.1
  encrypt: ^4.1.0
  do_core:
    path: packages/do_core
  do_common:
    path: packages/do_common

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.4
  bloc_test: ^7.1.0
  mockito: ^4.1.3
  json_serializable: ^3.5.0
  build_runner: ^1.10.4
  retrofit_generator: ^1.4.0

flutter_intl:
  enabled: true
  class_name: DongkapLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/alquran.png"
  adaptive_icon_foreground: "assets/images/alquran_foreground.png"
  adaptive_icon_background: "#21A7FF"
  adaptive_icon_padding: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/avatars/
    - assets/eva_icons/fill/svg/
    - assets/eva_icons/outline/svg/
    - assets/icons/
    - assets/images/
    - assets/surah/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 400
    - family: IsepMisbah
      fonts:
        - asset: assets/fonts/IsepMisbah.ttf
