name: do_theme
description: Library Theme.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.1
